<?php
$funcionarios = [
    ["funcionario" => "Paulo Medeiros",    "capa" => "imagens/funcionarios/paulo.png",   "funcao" => "Proprietário"], //paulo
    ["funcionario" => "Silvia Medeiros",   "capa" => "imagens/funcionarios/silvia.png",  "funcao" => "Proprietária"], //silvia
    ["funcionario" => "Felipe Medeiros",      "capa" => "imagens/funcionarios/felipe.png",  "funcao" => "Vendedor"], //felipe
    ["funcionario" => "Claudinei Nazário",    "capa" => "imagens/funcionarios/nei.png",     "funcao" => "Montador"], //nei
    ["funcionario" => "Larissa Carvalho",     "capa" => "imagens/funcionarios/larissa.png", "funcao" => "Caixa"], //larissa
    ["funcionario" => "Nataly Carvalho",      "capa" => "imagens/funcionarios/nataly.png",  "funcao" => "Vendedora"], //nataly
    ["funcionario" => "Edcarlo Oliveira",     "capa" => "imagens/funcionarios/edcarlo.png", "funcao" => "Montador"]  //edicarlos
];

$categoriaProd = [
    ["nome" => "Cozinhas",      "imagem" => "imagens/planejados/cozinha planejada cinza clara.jpg"],
    ["nome" => "Guarda Roupas", "imagem" => "imagens/moveis/g.r 6portas marrom.jpg"],
    ["nome" => "Sofás",         "imagem" => "imagens/Estofados/Sofa Preto 4p.jpg"],
    ["nome" => "Camas",         "imagem" => "imagens/moveis/box lazari.jpg"],
    ["nome" => "Mesas",         "imagem" => "imagens/moveis/conjunto de mesa.jpg"],
    ["nome" => "Eletros",       "imagem" => "imagens/eletros/geladeira 3 portas.jpg"]
];

$moveis = [
    [
        "nome" => "Cristaleira Alta Linz",
        "valorAP" => "10x de R$263,00 sem Juros",
        "valorAV" => "R$2.630,00",
        "valorAnt" => "R$2.900,00",
        "foto" => "imagens/Moveis/cristaleira alta linz.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não",
    ],

    [
        "nome" => "Cristaleira Baixa Linz",
        "valorAP" => "10x de R$17,20 sem Juros",
        "valorAV" => "R$1.720,00",
        "valorAnt" => "R$2.000,00",
        "foto" => "imagens/planejados/cozinha planejada cinza clara.jpg",
        "moveis" => "Não",
        "planejados" => "Sim",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não",
    ],

    [
        "nome" => "Cristaleira Baixa Linz",
        "valorAP" => "10x de R$17,20 sem Juros",
        "valorAV" => "R$1.720,00",
        "valorAnt" => "R$2.000,00",
        "foto" => "imagens/moveis/box lazari.jpg",
        "moveis" => "Não",
        "planejados" => "Não",
        "estofados" => "Sim",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não",
    ],

    [
        "nome" => "Cristaleira Baixa Linz",
        "valorAP" => "10x de R$17,20 sem Juros",
        "valorAV" => "R$1.720,00",
        "valorAnt" => "R$2.000,00",
        "foto" => "imagens/eletros/geladeira 3 portas.jpg",
        "moveis" => "Não",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não",
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],
    [
        "nome" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],

];

?>;