<?php
$funcionarios = [
    ["funcionario" => "Paulo Medeiros",    "capa" => "images/funcionarios."], //paulo
    ["funcionario" => "Silvia Medeiros",   "capa" => "images/funcionarios"], //silvia
    ["funcionario" => "Felipe Medeiros",   "capa" => "images/funcionarios"], //felipe
    ["funcionario" => "Nataly Carvalho",   "capa" => "images/funcionarios/nataly.jpg"], //nataly
    ["funcionario" => "Larissa Araújo",    "capa" => "images/funcionarios/larissa.jpg"], //larissa
    ["funcionario" => "Claudinei Bezerra", "capa" => "images/funcionarios/nei.jpg"], //nei
    ["funcionario" => "Edicarlo Oliveira", "capa" => "images/funcionarios/edcarlo.jpg"]  //edicarlos
];
?>;

<?php
$categoriaProd = [
    ["nome" => "Cozinhas",      "imagem" => "imagens/planejados/cozinha planejada cinza clara.jpg"],
    ["nome" => "Guarda Roupas", "imagem" => "imagens/moveis/g.r 6portas marrom.jpg"],
    ["nome" => "Sofás",         "imagem" => "imagens/Estofados/Sofa Preto 4p.jpg"],
    ["nome" => "Camas",         "imagem" => "imagens/moveis/box lazari.jpg"],
    ["nome" => "Mesas",         "imagem" => "imagens/moveis/conjunto de mesa.jpg"],
    ["nome" => "Eletros",       "imagem" => "imagens/eletros/geladeira 3 portas.jpg"]
];
?>;

<?php
$moveis = [
    [
        "moveis" => "Cristaleira Alta Linz",
        "valorAP" => "10x de R$263,00 sem Juros",
        "valorAV" => "R$2.630,00",
        "valorAnt" => "R$2.900,00",
        "foto" => "imagens/Moveis/cristaleira alta linz.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não",
    ],

    [
        "moveis" => "Cristaleira Baixa Linz",
        "valorAP" => "10x de R$17,20 sem Juros",
        "valorAV" => "R$1.720,00",
        "valorAnt" => "R$2.000,00",
        "foto" => "imagens/Moveis/cristaleria baixa Linz.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não",
    ],

    [
        "moveis" => "Roupeiro Vancouver - Carraro",
        "valorAP" => "10x de R$249,00 sem Juros",
        "valorAV" => "R$2.490,00",
        "valorAnt" => "R$2.800,00",
        "foto" => "imagens/Moveis/g.r 6portas marrom.jpg",
        "moveis" => "Sim",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não"
    ],

    [
        "moveis" => "Cristaleira Alta Linz",
        "valorAP" => "10x de R$263,00 sem Juros",
        "valorAV" => "R$2.630,00",
        "valorAnt" => "R$2.900,00",
        "foto" => "imagens/Moveis/cristaleira alta linz.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não",
    ],

    [
        "moveis" => "Cristaleira Alta Linz",
        "valorAP" => "10x de R$263,00 sem Juros",
        "valorAV" => "R$2.630,00",
        "valorAnt" => "R$2.900,00",
        "foto" => "imagens/Moveis/cristaleira alta linz.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não",
    ],

    [
        "moveis" => "Cristaleira Alta Linz",
        "valorAP" => "10x de R$263,00 sem Juros",
        "valorAV" => "R$2.630,00",
        "valorAnt" => "R$2.900,00",
        "foto" => "imagens/Moveis/cristaleira alta linz.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não",
    ],

    [
        "moveis" => "Cristaleira Alta Linz",
        "valorAP" => "10x de R$263,00 sem Juros",
        "valorAV" => "R$2.630,00",
        "valorAnt" => "R$2.900,00",
        "foto" => "imagens/Moveis/cristaleira alta linz.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não",
    ],

    [
        "moveis" => "Cristaleira Alta Linz",
        "valorAP" => "10x de R$263,00 sem Juros",
        "valorAV" => "R$2.630,00",
        "valorAnt" => "R$2.900,00",
        "foto" => "imagens/Moveis/cristaleira alta linz.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não",
    ],

    [
        "moveis" => "Cristaleira Alta Linz",
        "valorAP" => "10x de R$263,00 sem Juros",
        "valorAV" => "R$2.630,00",
        "valorAnt" => "R$2.900,00",
        "foto" => "imagens/Moveis/cristaleira alta linz.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não",
    ],

    [
        "moveis" => "Cristaleira Alta Linz",
        "valorAP" => "10x de R$263,00 sem Juros",
        "valorAV" => "R$2.630,00",
        "valorAnt" => "R$2.900,00",
        "foto" => "imagens/Moveis/cristaleira alta linz.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não",
    ],

    [
        "moveis" => "Cristaleira Alta Linz",
        "valorAP" => "10x de R$263,00 sem Juros",
        "valorAV" => "R$2.630,00",
        "valorAnt" => "R$2.900,00",
        "foto" => "imagens/Moveis/cristaleira alta linz.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não",
    ],

    [
        "moveis" => "Cristaleira Alta Linz",
        "valorAP" => "10x de R$263,00 sem Juros",
        "valorAV" => "R$2.630,00",
        "valorAnt" => "R$2.900,00",
        "foto" => "imagens/Moveis/cristaleira alta linz.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não",
    ],

    [
        "moveis" => "Cristaleira Alta Linz",
        "valorAP" => "10x de R$263,00 sem Juros",
        "valorAV" => "R$2.630,00",
        "valorAnt" => "R$2.900,00",
        "foto" => "imagens/Moveis/cristaleira alta linz.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não",
    ],

    [
        "moveis" => "Cristaleira Alta Linz",
        "valorAP" => "10x de R$263,00 sem Juros",
        "valorAV" => "R$2.630,00",
        "valorAnt" => "R$2.900,00",
        "foto" => "imagens/Moveis/cristaleira alta linz.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não",
    ],

    [
        "moveis" => "Cristaleira Alta Linz",
        "valorAP" => "10x de R$263,00 sem Juros",
        "valorAV" => "R$2.630,00",
        "valorAnt" => "R$2.900,00",
        "foto" => "imagens/Moveis/cristaleira alta linz.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não",
    ],

    [
        "moveis" => "Cristaleira Alta Linz",
        "valorAP" => "10x de R$263,00 sem Juros",
        "valorAV" => "R$2.630,00",
        "valorAnt" => "R$2.900,00",
        "foto" => "imagens/Moveis/cristaleira alta linz.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não",
    ],

    [
        "moveis" => "Cristaleira Alta Linz",
        "valorAP" => "10x de R$263,00 sem Juros",
        "valorAV" => "R$2.630,00",
        "valorAnt" => "R$2.900,00",
        "foto" => "imagens/Moveis/cristaleira alta linz.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não",
    ],

    [
        "moveis" => "Cristaleira Alta Linz",
        "valorAP" => "10x de R$263,00 sem Juros",
        "valorAV" => "R$2.630,00",
        "valorAnt" => "R$2.900,00",
        "foto" => "imagens/Moveis/cristaleira alta linz.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não",
    ],

    [
        "moveis" => "Cristaleira Alta Linz",
        "valorAP" => "10x de R$263,00 sem Juros",
        "valorAV" => "R$2.630,00",
        "valorAnt" => "R$2.900,00",
        "foto" => "imagens/Moveis/cristaleira alta linz.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não",
    ],

    [
        "moveis" => "Cristaleira Alta Linz",
        "valorAP" => "10x de R$263,00 sem Juros",
        "valorAV" => "R$2.630,00",
        "valorAnt" => "R$2.900,00",
        "foto" => "imagens/Moveis/cristaleira alta linz.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não",
    ],

    [
        "moveis" => "Cristaleira Alta Linz",
        "valorAP" => "10x de R$263,00 sem Juros",
        "valorAV" => "R$2.630,00",
        "valorAnt" => "R$2.900,00",
        "foto" => "imagens/Moveis/cristaleira alta linz.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não",
    ],

    [
        "moveis" => "Cristaleira Alta Linz",
        "valorAP" => "10x de R$263,00 sem Juros",
        "valorAV" => "R$2.630,00",
        "valorAnt" => "R$2.900,00",
        "foto" => "imagens/Moveis/cristaleira alta linz.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não",
    ],

    [
        "moveis" => "Cristaleira Alta Linz",
        "valorAP" => "10x de R$263,00 sem Juros",
        "valorAV" => "R$2.630,00",
        "valorAnt" => "R$2.900,00",
        "foto" => "imagens/Moveis/cristaleira alta linz.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não",
    ],

    [
        "moveis" => "Cristaleira Alta Linz",
        "valorAP" => "10x de R$263,00 sem Juros",
        "valorAV" => "R$2.630,00",
        "valorAnt" => "R$2.900,00",
        "foto" => "imagens/Moveis/cristaleira alta linz.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não",
    ],

    [
        "moveis" => "Cristaleira Alta Linz",
        "valorAP" => "10x de R$263,00 sem Juros",
        "valorAV" => "R$2.630,00",
        "valorAnt" => "R$2.900,00",
        "foto" => "imagens/Moveis/cristaleira alta linz.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não",
    ],

    [
        "moveis" => "Cristaleira Alta Linz",
        "valorAP" => "10x de R$263,00 sem Juros",
        "valorAV" => "R$2.630,00",
        "valorAnt" => "R$2.900,00",
        "foto" => "imagens/Moveis/cristaleira alta linz.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não",
    ],

    [
        "moveis" => "Cristaleira Alta Linz",
        "valorAP" => "10x de R$263,00 sem Juros",
        "valorAV" => "R$2.630,00",
        "valorAnt" => "R$2.900,00",
        "foto" => "imagens/Moveis/cristaleira alta linz.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não",
    ],

    [
        "moveis" => "Cristaleira Alta Linz",
        "valorAP" => "10x de R$263,00 sem Juros",
        "valorAV" => "R$2.630,00",
        "valorAnt" => "R$2.900,00",
        "foto" => "imagens/Moveis/cristaleira alta linz.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não",
    ],

    [
        "moveis" => "Cristaleira Alta Linz",
        "valorAP" => "10x de R$263,00 sem Juros",
        "valorAV" => "R$2.630,00",
        "valorAnt" => "R$2.900,00",
        "foto" => "imagens/Moveis/cristaleira alta linz.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não",
    ],

    [
        "moveis" => "Cristaleira Alta Linz",
        "valorAP" => "10x de R$263,00 sem Juros",
        "valorAV" => "R$2.630,00",
        "valorAnt" => "R$2.900,00",
        "foto" => "imagens/Moveis/cristaleira alta linz.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não",
    ],

    [
        "moveis" => "Cristaleira Alta Linz",
        "valorAP" => "10x de R$263,00 sem Juros",
        "valorAV" => "R$2.630,00",
        "valorAnt" => "R$2.900,00",
        "foto" => "imagens/Moveis/cristaleira alta linz.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não",
    ],

    [
        "moveis" => "Cristaleira Alta Linz",
        "valorAP" => "10x de R$263,00 sem Juros",
        "valorAV" => "R$2.630,00",
        "valorAnt" => "R$2.900,00",
        "foto" => "imagens/Moveis/cristaleira alta linz.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não",
    ],

    [
        "moveis" => "Cristaleira Alta Linz",
        "valorAP" => "10x de R$263,00 sem Juros",
        "valorAV" => "R$2.630,00",
        "valorAnt" => "R$2.900,00",
        "foto" => "imagens/Moveis/cristaleira alta linz.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "categoria" => "armario",
        "novidade" => "Não",
    ],

];

?>;