<?php
$funcionarios = [
    ["funcionario" => "Paulo Medeiros",    "capa" => "imagens/funcionarios/paulo.png",   "funcao" => "Proprietário"], //paulo
    ["funcionario" => "Silvia Medeiros",   "capa" => "imagens/funcionarios/silvia.png",  "funcao" => "Proprietária"], //silvia
    ["funcionario" => "Felipe Medeiros",      "capa" => "imagens/funcionarios/felipe.png",  "funcao" => "Vendedor"], //felipe
    ["funcionario" => "Claudinei Nazário",    "capa" => "imagens/funcionarios/nei.png",     "funcao" => "Montador"], //nei
    ["funcionario" => "Larissa Carvalho",     "capa" => "imagens/funcionarios/larissa.png", "funcao" => "Caixa"], //larissa
    ["funcionario" => "Nataly Carvalho",      "capa" => "imagens/funcionarios/nataly.png",  "funcao" => "Vendedora"], //nataly
    ["funcionario" => "Edcarlo Oliveira",     "capa" => "imagens/funcionarios/edcarlo.png", "funcao" => "Montador"]  //edicarlos
];

$categoriaProd = [
    ["nome" => "Cozinhas",      "imagem" => "imagens/planejados/cozinha planejada cinza clara.jpg"],
    ["nome" => "Guarda Roupas", "imagem" => "imagens/moveis/g.r 6portas marrom.jpg"],
    ["nome" => "Sofás",         "imagem" => "imagens/Estofados/Sofa Preto 4p.jpg"],
    ["nome" => "Camas",         "imagem" => "imagens/moveis/box lazari.jpg"],
    ["nome" => "Mesas",         "imagem" => "imagens/moveis/conjunto de mesa.jpg"],
    ["nome" => "Eletros",       "imagem" => "imagens/eletros/geladeira 3 portas.jpg"]
];

$nomeClasseProd = [
    ["nome" => "Móveis",     "href" => "produto?categoria=moveis",     "imagem" => "imagens/moveis/Roupeiro-Mozate-Henn.jpg"],
    ["nome" => "Planejados", "href" => "produto?categoria=planejados", "imagem" => "imagens/planejados/cozinha clara e geladeira.jpg"],
    ["nome" => "Estofados",  "href" => "produto?categoria=estofados",  "imagem" => "imagens/estofados/sofa preto 4p.jpg"],
    ["nome" => "Eletros",    "href" => "produto?categoria=eletros",    "imagem" => "imagens/eletros/geladeira 3 portas.jpg"],
];

$moveis = [
    [
        "nome" => "Roupeiro Capri Carraro 6 Portas Cinza",
        "valorAP" => "10x de R$344,00",
        "valorAV" => "R$3.440,00",
        "valorAnt" => "",
        "foto" => "imagens/Moveis/Roupeiro capri-carraro-6portas.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "novidade" => "Não",
    ],
    [
        "nome" => "Roupeiro Cover 6 Portas",
        "valorAP" => "10x de R$1830,00",
        "valorAV" => "R$1.599,00",
        "valorAnt" => "",
        "foto" => "imagens/Moveis/roupeiro-cover-6-portas.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "novidade" => "Não",
    ],
    [
        "nome" => "Roupeiro Loop Lopas 6 Portas",
        "valorAP" => "10x de R$442,00",
        "valorAV" => "R$3.899,00",
        "valorAnt" => "",
        "foto" => "imagens/moveis/Roupeiro-loop-lopas.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "novidade" => "Não",
    ],
    [
        "nome" => "Roupeiro Mozate Henn",
        "valorAP" => "10x de R$418,00",
        "valorAV" => "R$3.499,99",
        "valorAnt" => "",
        "foto" => "imagens/moveis/Roupeiro-Mozate-Henn.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "novidade" => "Não",
    ],
    [
        "nome" => "Multiuso Londres com Chave Freijó Off White",
        "valorAP" => "10x de R$47,00",
        "valorAV" => "R$399,90",
        "valorAnt" => "",
        "foto" => "imagens/Moveis/Multiuso-Londres-com-chave-freijó-off-white.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "novidade" => "Sim",
    ],
    [
        "nome" => "Roupeiro Capelinha 4 Portas",
        "valorAP" => "10x de R$110,00",
        "valorAV" => "R$969,90",
        "valorAnt" => "",
        "foto" => "imagens/Moveis/roupeiro-capelinha.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "novidade" => "Não",
    ],
    [
        "nome" => "Roupeiro Flora Henn",
        "valorAP" => "10x de R$214,00",
        "valorAV" => "R$1819,90",
        "valorAnt" => "",
        "foto" => "imagens/Moveis/guarda-roupa-6p-branco.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "novidade" => "Não",
    ],
    [
        "nome" => "Roupeiro Vancouver Carraro",
        "valorAP" => "10x de R$290,00",
        "valorAV" => "R$2900,00",
        "valorAnt" => "",
        "foto" => "imagens/Moveis/g.r-6portas-marrom.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "novidade" => "Não",
    ],
    [
        "nome" => "Roupeiro Capelinha 6 Portas",
        "valorAP" => "10x de R$123,00",
        "valorAV" => "R$999,90",
        "valorAnt" => "",
        "foto" => "imagens/Moveis/guarda-roupas-capelinha-6p.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "novidade" => "Não",
    ],
    [
        "nome" => "Multiuso Londres com Chave Freijó Branco",
        "valorAP" => "10x de R$47,00",
        "valorAV" => "R$399,90",
        "valorAnt" => "",
        "foto" => "imagens/Moveis/Multiuso-Londres-com-chave-freijó-branco.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "novidade" => "Sim",
    ],
    [
        "nome" => "Cristaleira Alta Linz",
        "valorAP" => "10x de R$263,00",
        "valorAV" => "R$2.630,00",
        "valorAnt" => "",
        "foto" => "imagens/Moveis/cristaleira-alta-linz.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "novidade" => "Não",
    ],
    [
        "nome" => "Cristaleira Baixa Linz",
        "valorAP" => "10x de R$172,00",
        "valorAV" => "R$1.720,00",
        "valorAnt" => "",
        "foto" => "imagens/Moveis/cristaleria-baixa-Linz.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "novidade" => "Não",
    ],
    [
        "nome" => "estante organizadora",
        "valorAP" => "10x de R$65,00",
        "valorAV" => "R$650,00",
        "valorAnt" => "",
        "foto" => "imagens/Moveis/Prateleira-Escritorio.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "novidade" => "Não",
    ],
    [
        "nome" => "Multiuso Fiorello Preto",
        "valorAP" => "10x de R$47,00",
        "valorAV" => "R$399,90",
        "valorAnt" => "",
        "foto" => "imagens/Moveis/novidade-Multiuso-fiorello.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "novidade" => "Sim",
    ],
    [
        "nome" => "Guarda Roupa Dubai Preto.jpg",
        "valorAP" => "10x de R$349,99",
        "valorAV" => "R$3499,99",
        "valorAnt" => "",
        "foto" => "imagens/Moveis/guarda-roupa-dubai-preto.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "novidade" => "Sim",
    ],
    /////////////parte 2
    [
        "nome" => "Guarda Roupa Dubai Preto.jpg",
        "valorAP" => "10x de R$349,99",
        "valorAV" => "R$3499,99",
        "valorAnt" => "",
        "foto" => "imagens/Moveis/guarda-roupa-dubai-preto.jpg",
        "moveis" => "Sim",
        "planejados" => "Não",
        "estofados" => "Não",
        "eletros" => "Não",
        "maisVendido" => "Não",
        "novidade" => "Sim",
    ],
];


?>;