<?php

namespace App\Proxies\__CG__\App\Model;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Produtos extends \App\Model\Produtos implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'data_cadastro' => [parent::class, 'data_cadastro', null, 16],
        "\0".parent::class."\0".'descricao' => [parent::class, 'descricao', null, 16],
        "\0".parent::class."\0".'diretorio_imagem' => [parent::class, 'diretorio_imagem', null, 16],
        "\0".parent::class."\0".'eletros' => [parent::class, 'eletros', null, 16],
        "\0".parent::class."\0".'estofados' => [parent::class, 'estofados', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'maisVendido' => [parent::class, 'maisVendido', null, 16],
        "\0".parent::class."\0".'moveis' => [parent::class, 'moveis', null, 16],
        "\0".parent::class."\0".'novidade' => [parent::class, 'novidade', null, 16],
        "\0".parent::class."\0".'planejados' => [parent::class, 'planejados', null, 16],
        "\0".parent::class."\0".'precoAP' => [parent::class, 'precoAP', null, 16],
        "\0".parent::class."\0".'precoAV' => [parent::class, 'precoAV', null, 16],
        "\0".parent::class."\0".'qtdeDisp' => [parent::class, 'qtdeDisp', null, 16],
        'data_cadastro' => [parent::class, 'data_cadastro', null, 16],
        'descricao' => [parent::class, 'descricao', null, 16],
        'diretorio_imagem' => [parent::class, 'diretorio_imagem', null, 16],
        'eletros' => [parent::class, 'eletros', null, 16],
        'estofados' => [parent::class, 'estofados', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'maisVendido' => [parent::class, 'maisVendido', null, 16],
        'moveis' => [parent::class, 'moveis', null, 16],
        'novidade' => [parent::class, 'novidade', null, 16],
        'planejados' => [parent::class, 'planejados', null, 16],
        'precoAP' => [parent::class, 'precoAP', null, 16],
        'precoAV' => [parent::class, 'precoAV', null, 16],
        'qtdeDisp' => [parent::class, 'qtdeDisp', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
